n1 = float(input("Digite o primeiro numero: "))
n2 = float(input("Digite o segundo numero: "))

print(f"Soma: {n1 + n2}")
print(f"Concatenação: {str(n1) + str(int(n2))}")
print(f"Multiplicação de numeros: {n1 * n2}")
print(f"Multiplicação de strings: {str(n1) * int(n2)}")
print(f"Divisão: {n1 / n2}")
print(f"Divisão inteira: {n1 // n2}")
print(f"Exponenciação: {n1**n2}")
print(f"Modulo: {n1 % n2}")
